// Korrekte iNaturalist Taxon-IDs – verifiziert via iNaturalist API
// Für Kultivare ohne eigenes iNat-Taxon: Wikipedia als Bildquelle (preferWiki: true)
// wiki: Wikipedia-Artikeltitel (EN) für die Pflanzenart/-sorte

const TAXON_IDS = {
  // ── LAUBGEHÖLZE ──────────────────────────────────────────────────────────
  "acer-campestre":           { inat: 56193 },
  "acer-platanoides":         { inat: 54763 },
  "aesculus-hippocastanum":   { inat: 84298 },
  "amelanchier-lamarckii":    { inat: 1091496 },
  "berberis-thunbergii-atropurpurea": { wiki: "Berberis thunbergii", preferWiki: true, inat: 58727 },
  "betula-pendula":           { inat: 83992 },
  "buddleja-cultivars":       { inat: 64571 },
  "buxus-sempervirens":       { inat: 133397 },
  "calluna-vulgaris":         { inat: 119450 },
  "carpinus-betulus":         { inat: 55801 },
  "cornus-alba-sibirica":     { inat: 124879 },
  "cornus-mas":               { inat: 55858 },
  "corylus-avellana":         { inat: 54491 },
  "corylus-avellana-contorta":{ localImage: "Korkenzieherhasel.jpeg", wiki: "Contorted hazel", preferWiki: true, inat: 54491, commonsSearch: "Corylus avellana Contorta twisted branches" },
  "cotoneaster-dammeri":      { inat: 160946 },
  "cotoneaster-divaricatus":  { inat: 160947 },
  "cytisus-scoparius":        { inat: 48538 },
  "deutzia-gracilis":         { inat: 452296 },
  "erica-carnea":             { inat: 56306 },
  "euonymus-alatus":          { inat: 117433 },
  "euonymus-fortunei":        { inat: 130893 },
  "fagus-sylvatica":          { inat: 54227 },
  "fargesia-murieliae":       { inat: 480755 },
  "forsythia-intermedia":     { inat: 411276 },
  "fraxinus-excelsior":       { inat: 125440 },
  "hamamelis-intermedia":     { inat: 1231667 },
  "hibiscus-syriacus":        { inat: 126585 },
  "hippophae-rhamnoides":     { inat: 163812 },
  "hydrangea-macrophylla":    { inat: 122034 },
  "hypericum-calycinum":      { inat: 77481 },
  "ilex-aquifolium":          { inat: 53856 },
  "ilex-crenata-convexa":     { inat: 133240 },
  "jasminum-nudiflorum":      { inat: 164232 },
  "juglans-regia":            { inat: 63935 },
  "kerria-japonica":          { inat: 125788 },
  "kolkwitzia-amabilis":      { inat: 52501 },
  "laburnum-watereri-vossii": { inat: 128549 },
  "ligustrum-vulgare":        { inat: 119805 },
  "lonicera-nitida":          { inat: 777468 },
  "magnolia-soulangeana":     { inat: 204586 },
  "mahonia-aquifolium":       { inat: 126887 },
  "pachysandra-terminalis":   { inat: 142928 },
  "philadelphus-coronarius":  { inat: 52468 },
  "pieris-japonica":          { inat: 127181 },
  "platanus-hispanica":       { inat: 552449 },
  "potentilla-fruticosa":     { inat: 76606 },
  "prunus-cerasifera-nigra":  { wiki: "Prunus cerasifera", preferWiki: true, inat: 55837 },
  "prunus-laurocerasus":      { inat: 61432 },
  "prunus-serrulata":         { inat: 125742 },
  "quercus-robur":            { inat: 56133 },
  "quercus-rubra":            { inat: 49005 },
  "rhododendron-cultivars":   { inat: 49487 },
  "ribes-sanguineum":         { inat: 53435 },
  "robinia-pseudoacacia":     { inat: 56088 },
  "rosa-rugosa":              { inat: 83653 },
  "salix-alba-tristis":       { localImage: "Trauerweide.jpeg", inat: 1377466, wiki: "Salix × sepulcralis", commonsSearch: "Salix sepulcralis chrysocoma weeping willow golden" },
  "sambucus-nigra":           { inat: 765394 },
  "sorbus-aucuparia":         { inat: 56063 },
  "spiraea-arguta":           { localImage: "Brautspiere.jpeg", wiki: "Spiraea arguta", commonsSearch: "Spiraea arguta bridal wreath white flowers" },
  "spiraea-japonica":         { inat: 125790 },
  "spiraea-vanhouttei":       { localImage: "Prachtspiere_vanhouttei.jpg", inat: 171131, commonsSearch: "Spiraea vanhouttei flowering white shrub" },
  "syringa-vulgaris":         { inat: 83072 },
  "tilia-cordata":            { inat: 132600 },
  "viburnum-lantana":         { inat: 124741 },
  "viburnum-rhytidophyllum":  { inat: 128688 },
  "viburnum-bodnantense-dawn":{ inat: 523141 },
  "vinca-minor":              { inat: 55844 },
  "weigela-cultivars":        { inat: 153104 },

  // ── NADELGEHÖLZE ─────────────────────────────────────────────────────────
  "abies-nordmanniana":       { inat: 136894 },
  "cedrus-atlantica-glauca":  { wiki: "Cedrus atlantica", preferWiki: true, inat: 136234 },
  "chamaecyparis-lawsoniana-columnaris": { inat: 76237 },
  "chamaecyparis-obtusa-nana-gracilis":  { inat: 133369 },
  "ginkgo-biloba":            { inat: 64350 },
  "juniperus-communis":       { inat: 58725 },
  "larix-decidua":            { localImage: "Europaeische_Laerche.jpeg", inat: 59747, commonsSearch: "Larix decidua European larch tree" },
  "picea-omorika":            { inat: 135773 },
  "picea-pungens":            { inat: 119092 },
  "pinus-sylvestris":         { inat: 58722 },
  "pinus-nigra":              { inat: 135790 },
  "taxus-baccata":            { inat: 47553 },
  "taxus-baccata-fastigiata": { localImage: "Saeuleneibe.jpeg", wiki: "Irish Yew", preferWiki: true, inat: 47553, commonsSearch: "Taxus baccata Fastigiata columnar Irish yew" },
  "thuja-occidentalis":       { inat: 54037 },
  "tsuga-canadensis":         { inat: 48734 },

  // ── KLETTERPFLANZEN ──────────────────────────────────────────────────────
  "clematis-cultivars":       { inat: 49877 },
  "fallopia-baldschuanica":   { inat: 77128 },
  "hedera-helix":             { inat: 55882 },
  "hydrangea-petiolaris":     { inat: 410578 },
  "parthenocissus-tricuspidata": { inat: 166162 },
  "wisteria-sinensis":        { inat: 127306 },

  // ── STAUDEN ──────────────────────────────────────────────────────────────
  "achillea-filipendulina":   { inat: 157924 },
  "aconitum-napellus":        { inat: 131201 },
  "alchemilla-mollis":        { inat: 56022 },
  "astilbe-arendsii":         { localImage: "Prachtspiere_arendsii.jpeg", inat: 51806, commonsSearch: "Astilbe arendsii garden perennial flowers" },
  "bergenia-cordifolia":      { inat: 127228 },
  "carex-morrowii":           { localImage: "Japan_Segge.jpeg", inat: 468050, commonsSearch: "Carex morrowii Japanese sedge grass" },
  "delphinium-elatum":        { inat: 161664 },
  "digitalis-purpurea":       { inat: 53983 },
  "echinacea-purpurea":       { inat: 48627 },
  "geranium-macrorrhizum":    { inat: 320685 },
  "heuchera-micrantha":       { inat: 51274 },
  "hosta-cultivars":          { inat: 82095 },
  "lavandula-angustifolia":   { inat: 133395 },
  "nepeta-faassenii":         { inat: 410913 },
  "primula-vulgaris":         { inat: 56136 },
  "rudbeckia-fulgida":        { inat: 142654 },
  "sedum-telephium":          { inat: 84031 },
  "waldsteinia-ternata":      { inat: 523985 },

  // ── ZWIEBELPFLANZEN ──────────────────────────────────────────────────────
  "crocus-vernus":            { inat: 1371920 },
  "galanthus-nivalis":        { inat: 51606 },
  "narcissus-pseudonarcissus":{ inat: 55848 },
  "tulipa-cultivars":         { inat: 55800 },

  // ── WILDKRÄUTER ──────────────────────────────────────────────────────────
  "aegopodium-podagraria":    { inat: 51741 },
  "atriplex-patula":          { inat: 60175 },
  "bellis-perennis":          { inat: 55563 },
  "cirsium-arvense":          { inat: 60132 },
  "convolvulus-arvensis":     { inat: 53021 },
  "elymus-repens":            { inat: 60284 },
  "equisetum-arvense":        { inat: 52724 },
  "galinsoga-parviflora":     { inat: 48178 },
  "senecio-vulgaris":         { inat: 53211 },
  "stellaria-media":          { inat: 1087592 },
  "taraxacum-ruderalia":      { inat: 47602 },
  "urtica-dioica":            { inat: 51884 },
  "urtica-urens":             { inat: 53315 },
};
